config/routes.rb
Rails.application.routes.draw do
  post '/friendships/update/:id', to: 'friendships#update', as: 'friend'
  post '/friendships/create/:id', to: 'friendships#create', as: 'create_friend'
  
  get 'user/show', as: 'user_profile'
  get 'user/index', to: 'user#index', as: 'friends_list'
  get 'user/profile/:id', to: 'user#profile', as: 'friend_profile'

  get 'home/index'
  devise_for :users
  resources :transactions, except: %i[show]

  get 'transaction/new/:group_id', to: 'transactions#new_with_group', as: 'new_with_group'
  
  get 'transaction/user', to: 'transactions#index_by_user', as: 'index_by_user'

  get 'transaction/group/:group_id', to: 'transactions#index_by_group', as: 'index_by_group'

  get 'home/', to: 'home#index', as: 'home'
  resources :groups, except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, :icon, presence: true
  belongs_to :user, foreign_key: 'user_id'
  has_many :transactions
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @transactions = @group.transactions.all
  end

  # GET /groups/new
  def new
    @group = current_user.groups.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.new(group_params)
    @group.icon = params[:icon]
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
      else
        format.html { redirect_to @group, notice: 'Error please fill all fields' }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_list(groups)
    @content = content_tag(:span, '')
    groups.collect do |c|
      @content.concat(
        content_tag(:div, class: 'group-card') do
          concat(image_tag(c.icon.to_s) + ' ' +
                 content_tag(:span, c.name) + ' ' +
                 content_tag(:a, href: "groups/#{c.id}") do
                   'show'
                 end)
        end
      )
    end
    @content
  end

  def select_icon
    icons = { 'car' => 'icons/car.png', \
              'travel' => 'icons/case.png', \
              'clothes' => 'icons/clothes.png', \
              'grocery' => 'icons/grocery.png', \
              'home' => 'icons/home.png', \
              'office' => 'icons/office.png', \
              'transport' => 'icons/transport.png' }

    @content = content_tag(:span, '')

    icons.each do |icon|
      @content.concat(
        content_tag(:div, class: 'form-radio-btn-item') do
          concat(
            content_tag(:div, class: 'card-body-rad form-inline card-radio-btn') do
              radio_button_tag(:icon, icon[1]) + ' ' +
              image_tag((icon[1]).to_s, class: 'card-img')
            end
          )
        end
      ) # content.concat
    end

    @content
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-input"  %>
  </div>

  <fieldset>
  <div class="form-radio-btn-item">
    <%= select_icon %>
  </div>
  </fieldset>

  <div class="actions">
    <%= form.submit class: "form-input"  %>
  </div>
<% end %>

app/views/groups/_transaction_card.html.erb
 <div class="card card-transaction">
    <div class="card-horizontal d-flex flex-row">
        <div class="img-wrapper">
            <%= image_tag  "#{transaction.group.icon}", class:"circle-img"%>
        </div>
        <div class="card-body">
            <h5><%= transaction.name %></h5>
            <span><%= transaction.description %></span>
            <span><%= "$ #{transaction.amount}" %></span>
        </div>
    </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<%=group_list(@groups)%>

<br>

<%= link_to 'New Group', new_group_path, class:'fake-button fixed-bottom' %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag  "#{@group.icon}" %>
</p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<div class="container" id="transactions">

  <%@transactions.each do |transaction|%>
        <%= render "transaction_card", transaction: transaction %>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= edit_btn(transaction.user_id,transaction.id) %></td>
        <td><%= delete_btn(transaction.user_id,transaction.id)%></td>
    </tr>
  <%end%>
  </tbody>
</table>  
</div>

<%= link_to 'New Transaction', new_with_group_path(@group.id), class: "fake-button fixed-bottom" %> 
<%= link_to 'Back', groups_path %>