config/routes.rb
Rails.application.routes.draw do
  post '/friendships/update/:id', to: 'friendships#update', as: 'friend'
  post '/friendships/create/:id', to: 'friendships#create', as: 'create_friend'
  
  get 'user/show', as: 'user_profile'
  get 'user/index', to: 'user#index', as: 'friends_list'
  get 'user/profile/:id', to: 'user#profile', as: 'friend_profile'

  get 'home/index'
  devise_for :users
  resources :transactions, except: %i[show]

  get 'transaction/new/:group_id', to: 'transactions#new_with_group', as: 'new_with_group'
  
  get 'transaction/user', to: 'transactions#index_by_user', as: 'index_by_user'

  get 'transaction/group/:group_id', to: 'transactions#index_by_group', as: 'index_by_group'

  get 'home/', to: 'home#index', as: 'home'
  resources :groups, except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, presence: true
  validates_length_of :name, minimum: 5, maximum: 30
  validates_uniqueness_of :name, :email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
  has_many :groups

  def grouped_trans
    transactions.map { |transaction| transaction unless transaction.group.nil? }.compact
  end

  def ungrouped_trans
    transactions.map { |transaction| transaction if transaction.group.nil? }.compact
  end

  def total_transaction(user_id)
    Transaction.where(user_id: user_id).sum(:amount)
    # @total =  user.transactions.inject(0) { |sum, t| sum + t.amount }
    # return @total
  end

  has_many :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
  has_many :friends, through: :friendships, class_name: 'User', foreign_key: 'user_id'

  def friends
    # rubocop:disable Lint/Void
    friends_array = friendships.map { |friendship| friendship.friend if friendship.confirmed }
    friends_array + inverse_friendships.map { |friendship| friendship.user if friendship.confirmed }
    friends_array.compact
    # rubocop:enable Lint/Void
  end

  def pending_friends
    friendships.map { |friendship| friendship.friend unless friendship.confirmed }.compact
  end

  def friend_request
    inverse_friendships.map { |friendship| friendship.user unless friendship.confirmed }.compact
  end

  def confirm_friend(user)
    ActiveRecord::Base.transaction do
      friendship = inverse_friendships.find_by user_id: user.id
      friendship.update!(confirmed: true)
      friendship.save
      inverse_rel = friendships.new(friend_id: user.id, confirmed: true)
      inverse_rel.save!
    end
  end

  def friend?(user)
    friends.include?(user)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user
  end

  def index
    @users = User.all
  end

  def profile
    set_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
  def display_avatar
    image_tag current_user.avatar.to_s
  end

  def friendship_helper
    if current_user.id == params[:id].to_i
      nil
    elsif current_user.friend?(User.find(params[:id]))
      'You are already friends'
    elsif current_user.pending_friends.include?(User.find(params[:id]))
      'Waiting for confirmation'
    elsif User.find(params[:id]).pending_friends.include?(current_user)
      link_to 'Accept friend', friend_path(params[:id]), method: :post
    else
      link_to 'Send friend request', create_friend_path(params[:id]), method: :post
    end
  end
end

app/views/user/index.html.erb
<section class="users-section">
  <ul class="users-list">
    <% @users.each do |user| %>
      
      <li>
        <div class = "container-profiles">
        <%= image_tag  "#{user.avatar}", class: "friend-avatar"%>
        Name: <%= user.name %>
        <span class="profile-link">
          <%= link_to 'See Profile',  friend_profile_path(user), class: 'profile-link' %>
        </span>
        </div>
      </li>
      
    <% end %>
  </ul>
</section>

app/views/user/profile.html.erb
<section class="user-section card-horizontal-rad">
  <div class = "card-body-rad"> 
  <h5><%= friendship_helper %></h5>
  <h2><%= "Name: #{@user.name}" %></h2>
  <%= image_tag  "#{@user.avatar}", class: "friend-avatar"%>
  <article class="timeline">
    <%= current_user.total_transaction(@user.id) if current_user.friend?(@user) %>    
  </article>
   </div>
</section>

app/views/user/show.html.erb
<div class="container-fluid container-custom" id="profile_links">
  <div class="vertical_user_card">
    <div class="avatar-wrapper">
      <%= display_avatar %>
    </div>
    <div class="nombre_user">
      <%=current_user.name%>
    </div>
  </div>
    <%= link_to  "My Transactions", index_by_user_path, :class => "link_button"%>
    <%= link_to  "My External Transactions", transactions_path, :class => "link_button"%>
    <%= link_to  "All groups",  groups_path, :class => "link_button"%>
    <%= link_to  "Friends",  friends_list_path, :class => "link_button"%>
</div>