config/routes.rb
Rails.application.routes.draw do
  post '/friendships/update/:id', to: 'friendships#update', as: 'friend'
  post '/friendships/create/:id', to: 'friendships#create', as: 'create_friend'
  
  get 'user/show', as: 'user_profile'
  get 'user/index', to: 'user#index', as: 'friends_list'
  get 'user/profile/:id', to: 'user#profile', as: 'friend_profile'

  get 'home/index'
  devise_for :users
  resources :transactions, except: %i[show]

  get 'transaction/new/:group_id', to: 'transactions#new_with_group', as: 'new_with_group'
  
  get 'transaction/user', to: 'transactions#index_by_user', as: 'index_by_user'

  get 'transaction/group/:group_id', to: 'transactions#index_by_group', as: 'index_by_group'

  get 'home/', to: 'home#index', as: 'home'
  resources :groups, except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = current_user.transactions.where(group_id: nil).includes(:group)
    @total = @transactions.sum(:amount)
  end

  def index_by_user
    @transactions = current_user.transactions.where.not(group_id: nil).includes(:group)
    @total = @transactions.inject(0) { |sum, t| sum + t.amount }
  end

  def index_by_group
    @group = Group.find(params[:group_id])
    @transactions = group.transactions.includes(:user)
    @total = @transactions.sum(:amount)
  end

  # GET /transactions/new
  def new
    @transaction = current_user.transactions.new
    @groups = Group.all.includes(:user)
  end

  def new_with_group
    set_group
    @transaction = @group.transactions.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    # rubocop:disable Style/NumericPredicate
    @transaction.group_id = nil if @transaction.group_id == 0
    # rubocop:enable Style/NumericPredicate
    @transaction.user_id = current_user.id if @transaction.user_id.nil?
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to '/transaction/user', notice: 'Transaction was successfully created.' }
      else
        format.html { redirect_to '/transaction/user', alert: 'Error in the transaction creation.' }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :description, :amount, :group_id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def edit_btn(author, trans_id)
    link_to 'Edit', edit_transaction_path(Transaction.find(trans_id)) if current_user.id == author
  end

  def get_icon(transaction)
    image_tag transaction.group.icon.to_s unless transaction.group.nil?
  end

  # rubocop:disable Layout/LineLength
  def delete_btn(author, trans_id)
    link_to 'Destroy', Transaction.find(trans_id), method: :delete, data: { confirm: 'Are you sure?' } if current_user.id == author
  end
  # rubocop:enable Layout/LineLength
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-input" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-input" %>
  </div>
  
  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "form-input" %>
  </div>
  
   <fieldset>
    <div class="form-radio-btn-item">
    <div class="card-body-rad form-inline card-radio-btn">
        <%=form.radio_button :group_id, 0 %>
        <label for = "0" class: "card-radio-btn-item"> NO GROUP </label>
    </div>
    <% @groups.each do |group|%>
      <div class="card-body-rad form-inline card-radio-btn">
        <%=form.radio_button :group_id, group.id %>
        <label for = "<%group.id%>" class: "card-radio-btn-item"> &nbsp<%= image_tag  "#{group.icon}", class: "card-img" %>&nbsp&nbsp<%= group.name %> </label>
      </div>
    <%end%>
    </div>
  </fieldset>


  <div class="actions">
    <%= form.submit class: "form-input"%>
  </div>
<% end %>

app/views/transactions/_transaction_card.html.erb
 <div class="card card-transaction">
    <div class="card-horizontal d-flex flex-row">
        <div class="img-wrapper">
          <%if !transaction.group.nil? %>
            <%= image_tag  "#{transaction.group.icon}", class:"circle-img"%>
          <%end%>
            
        </div>
        <div class="card-body">
            <h5><%= transaction.name %></h5>
            <span><%= transaction.description %></span>
            <span><%= "$ #{transaction.amount}" %></span>
        </div>
    </div>
</div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<div class="total-container">
  <div class="wrapper">Transactions</div>
  <div class="wrapper">Total $ <span><%=@total%></span></div>
</div>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>Name</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td>
          <%= get_icon(transaction) %>
        </td>
        <td><%= transaction.name %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.amount %></td>
        <td><%= edit_btn(transaction.user_id, transaction.id) %></td>
        <td><%= delete_btn(transaction.user_id, transaction.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path, class: "fake-button fixed-bottom" %>

app/views/transactions/index_by_group.html.erb
<div class="total-container">
  <div class="wrapper">Transactions</div>
  <div class="wrapper">Total $ <span><%=@total%></span></div>
</div>

    <% @transactions.each do |transaction| %>
        <%= render "transaction_card", transaction: transaction %>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class='fake-button'>
  <%= link_to 'New Transaction', new_transaction_path %>
</div>

app/views/transactions/index_by_user.html.erb
<div class="total-container">
  <div class="wrapper">Transactions</div>
  <div class="wrapper">Total $ <span><%=@total%></span></div>
</div>

<% @transactions.each do |transaction| %>
  <%= render "transaction_card", transaction: transaction %>
  <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
  <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
<br>


<%= link_to 'New Transaction', new_transaction_path, class:'fake-button fixed-bottom' %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', index_by_user_path %>

app/views/transactions/new_with_group.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<%= link_to 'Back', index_by_user_path %>